# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-WebService-OpenCellID
version:      0.04
version_from: lib/Geo/WebService/OpenCellID.pm
installdirs:  site
requires:
    base:                          0
    LWP::Simple:                   0
    strict:                        0
    Test::Simple:                  0.44
    URI:                           0
    warnings:                      0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
